### ISSUE TITLE
Úkol 1 mám hotový

### ISSUE THREAD

**Issue by PavlinaVagnerova** [PavlinaVagnerova/Programov-n--v-Pythonu#1]
@t-reezy Můžeš se na můj úkol 1 podívat, prosím? Díky Pavlína

**Comment by t-reezy** [comment]
@PavlinaVagnerova super :) 
K "základnímu" úkolu, nemám výhrady, vypadá to moc dobře.  Úkol značím jako splněný. 
Super, že se pustila i do bonusů. Tam ale vidím pár věcí na zlepšení. 
1. bonus - tam ti chybí ta abstraktní metoda `calculate_tax()`.
2. bonus - do enum třídy si rovnou můžeš uložit hodnoty jednotlivých koeficintů: 

```python 
class EnEstateType(enum.Enum):
    LAND = 0.85
    BULDING = 9
    FORREST = 0.35
    GARDEN = 2
```

 a rovnou pak můžeš instanci této třídy dát do kontruktoru: 

```python 
Estate("Brno", EnEstateType.GARDEN, 1000) 
```

a koeficient typu pozemku (v metodě `calculate_tax()` ) pak dostaneš jednoduše jako: 

```python 
koeficient = self.estate_type.value
```

3. bonus - skvělý ;) 

Doufám, že mé rychlé vysvětlení bylo srozumitelné. Kdyby ne, napiš, zkusím znovu. Případně se můžeme i domluvit na rychlém videohovoru, když budeš chtít.

**Comment by PavlinaVagnerova** [comment]
@t-reezy Ahoj, díky moc za tipy, jak bonusy dořešit :) Soubor s bonusy jsem podle tvých rad upravila, vypadá to, že funguje, tak snad to bude dobře :)
Díky předem za kontrolu
Pavlína
