### ISSUE TITLE
Úkol 2 mám hotový

### ISSUE THREAD

**Issue by PavlinaVagnerova** [PavlinaVagnerova/Programov-n--v-Pythonu#2]
@t-reezy Můžeš se na můj úkol 2 podívat, prosím?
Zatím jsem zpracovala jenom povinnou část, s bonusem si nějak nevím rady.
Díky Pavlína

**Comment by t-reezy** [comment]
Ahoj Pavlino, 
super, píšu splněno. 
Kdybys chtěla program vylepšit, je super třeba zkontrolovat status code:
```
if response.status_code == 200:
    response_json =respnse.json()
else:
    print("Chyba při vyhledávání")
```
tak když se stane, že uživatel zadá třeba chybné ičo, program uplně nespadne ;)
